number= float(input("enter name"))
print(type (number))
print(number)
number2= float(input("enter name"))
print(type (number2))
print(number2)
number3= float(input("enter name"))
print(type (number3))
print(number3)